# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b57d810dfb8be910902088b8d8c32512850c0b31f06b33838c4af2e03e8ec77ab325073d85c19169a93cd1e3212de3c5a5f61c194cde79a9d93ba00f4b52602

test:
  secret_key_base: 6040aeaca2af7818e1eb5c1f9de2c5120815456397455f68c805b6b8d5d2165ed9d6b5b26e09a59bcca317b7fd288e4d6ab3163b6eff5e7b2b319b70a15245cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
